export enum PerkType {
  PERMANENT = 'PERMANENT',
  TEMPORARY = 'TEMPORARY',
  CONSUMABLE = 'CONSUMABLE',
  EVENT_DRIVEN = 'EVENT_DRIVEN',
}

export enum BoostType {
  RENT_MULTIPLIER = 'RENT_MULTIPLIER',
  DICE_MODIFIER = 'DICE_MODIFIER',
  CASH_REWARD = 'CASH_REWARD',
  TAX_REDUCTION = 'TAX_REDUCTION',
  SPEED_BOOST = 'SPEED_BOOST',
}

export enum StackingRule {
  ADDITIVE = 'ADDITIVE',
  MULTIPLICATIVE = 'MULTIPLICATIVE',
  HIGHEST_ONLY = 'HIGHEST_ONLY',
  NON_STACKABLE = 'NON_STACKABLE',
}
